"""Initial migration.

Revision ID: 984397cb949f
Revises: 
Create Date: 2023-05-04 06:24:54.060256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984397cb949f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_table('produto')
    op.drop_table('Pedidos')
    op.drop_table('produtos')
    op.drop_table('Jogos')
    op.drop_table('Usuarios')
    op.drop_table('url_produto')
    op.drop_table('CategoriasTrocafone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoriasTrocafone',
    sa.Column('cod_categoria', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('cod_url', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome_categoria', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('url_categoria', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cod_categoria', name='PK__Categori__F052220797E4BAB7')
    )
    op.create_table('url_produto',
    sa.Column('cod_url', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('urlproduto', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cod_url', name='PK__url_prod__F240F2FF67EE39E6')
    )
    op.create_table('Usuarios',
    sa.Column('nickname', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('Jogos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('console', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('produtos',
    sa.Column('cod_produto', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nomeproduto', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('precoproduto', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('imagens', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('atributos', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cod_produto', name='PK__produtos__B3FE2EFDB9F33469')
    )
    op.create_table('Pedidos',
    sa.Column('cod_pedido', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cod_produto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('desconto', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('margem', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('cod_endereco', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cod_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('datacriacao', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('statuspedido', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('produto',
    sa.Column('cod_produto', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('preco', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('saldo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('marca', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cod_produto', name='PK_produto')
    )
    op.create_table('Orders',
    sa.Column('cod_pedido', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('referencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('sobrenome', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('statuspedido', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('pagamento', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cod_pedido', name='PK_orders')
    )
    # ### end Alembic commands ###
